### PR TITLE
[jjo] implement openstack-helm instrumentation at os/Makefile

### PR DESCRIPTION
**Pull request by jjo**
* Instrument charts packaging, `helm` running (including `helm template`
  and `helm inspect` to help previewing deploy and debugging)
* See `make -C os` for  sequenced targets
* Note that `make -C os deploy` still needs to be run, surely still many things to fix

### CODE REVIEW

**Comment by jjo** [comment]
Note you could safely verify this PR by running:
```
make init
make prep
make creds
make tests
```

**Comment by c0r0nel** [comment]
Small detail, make prep should check if helm is  present and at least stop gacefully.

**Comment by jjo** [comment]
> Small detail, make prep should check if helm is present and at least stop gacefully.

Good point, will add.

**Comment by c0r0nel** [comment]
> > Small detail, make prep should check if helm is present and at least stop gacefully.
> 
> Good point, will add.

It should be fine with just a small warning that also remeber to run helm init too. :)

**Comment by jjo** [comment]
> > > Small detail, make prep should check if helm is present and at least stop gacefully.
> > 
> > 
> > Good point, will add.
> 
> It should be fine with just a small warning that also remeber to run helm init too. :)

We already run helm init, prefer to completely (early) fail if not available, it's really required.

**Comment by jjo** [comment]
@c0r0nel PTAL, added at cbfef9d .

**Comment by jjo** [comment]
> Tested on my local machine, looks great!.

Thanks @c0r0nel, merging.
FYI got `keystone` deployed Ok in the actual cluster (although its script failing from openstack cli as we don't have an usable ingress yet (no metallb)), this validates several aspects of the proposal:
- openstack stateful layer (replicated mariadb and rabbitmq) working Ok, integrating perfectly with Rook provided storageclass (as expected)
- keystone is the "first" needed openstack service (identity), having deployed it ok paves the way for the remaining ones
/cc @navarrow-um

**Pull request merged**
